'use strict';
const G=window.GUIDE;
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const entry=id=>G.entries[id];
const navUrl=e=>{const p=e.pointId?G.points.find(p=>p.id===e.pointId):null;const query=p?.navQuery||e.name.replace('早餐','')+' '+e.place.replace(/[\u3400-\u9fff·]/g,' ');return 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(query)};
const pin='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2.5"/></svg>';
const dayNames=['周五','周六','周日'];
const dayDates=['10/9','10/10','10/11'];
const dayTasks=['下班出发','一整天看秋色','早点返程'];
const dayTitles=['先吃饭，再出发。','今天，秋色在路上。','看一眼湖，就往家开。'];
let routeId='gold', day=1, activeEntry=null, mediaMode='photo';
let picks={};try{picks=JSON.parse(localStorage.getItem('395-photo-guide-picks')||'{}')}catch{}
const route=()=>G.routes.find(r=>r.id===routeId);
function routes(){ $('#routes').innerHTML=G.routes.map((r,i)=>`<button class="route-pick" data-route="${r.id}" aria-pressed="${r.id===routeId}" aria-label="路线 ${i+1}，${r.name}"><img src="${r.image}" alt="${i===0?'South Lake Road 白杨实拍':'Silver Lake 湖边秋色实拍'}" width="460" height="190"><span class="route-check" aria-hidden="true">✓</span><span class="route-copy"><span class="route-num">0${i+1} / ${r.tag}</span><strong>${r.name}</strong><small>${r.label}</small></span></button>`).join(''); }
function photo(e,cls='stop-photo',lazy=true){const collage=['schat','toomeys'].includes(e.id);return `<button class="${cls} ${collage?'collage':''}" data-entry="${e.id}" aria-label="查看 ${esc(e.name)} 照片与推荐"><img src="${e.image}" alt="${esc(e.name)} · ${esc(e.credit)}" ${lazy?'loading="lazy"':''} decoding="async" width="640" height="430"><span class="photo-zoom" aria-hidden="true">⤢ 看照片</span></button>`;}
function time(event,category){return `<div class="time">${event.time}<span class="category">${category}</span></div>`;}
function stopCard(event,i){const e=entry(event.id);return `<article class="event stop-event" id="event-${i}">${time(event,'看风景')}<div class="stop-card"><div class="stop-top"><div class="place-line"><h3>${e.name}</h3><a class="nav-pin" href="${navUrl(e)}" target="_blank" rel="noopener" aria-label="导航到 ${esc(e.name)}">${pin}</a></div><p class="event-note">${event.note||e.dish}</p></div>${photo(e)}<p class="photo-credit">${esc(e.credit)}</p><div class="stop-bottom"><p>${e.dish}</p><button class="detail-button" data-entry="${e.id}">推荐 / 踩坑</button></div></div>${event.drive?`<p class="drive-next">${event.drive}</p>`:''}</article>`;}
function optionCard(id,key){const e=entry(id),chosen=picks[key]===id;return `<article class="option-card ${chosen?'chosen':''}" data-option="${id}">${photo(e,'option-photo')}<div class="option-inside"><p class="tag">${e.tag}</p><h4>${e.name}</h4><p class="dish">${e.dish}</p><p class="hint">${e.hint}</p><div class="option-actions"><a href="${navUrl(e)}" target="_blank" rel="noopener">地图 ↗</a><button class="choose" data-pick="${id}" data-key="${key}" aria-label="选择 ${esc(e.name)}" aria-pressed="${chosen}">${chosen?'✓ 已选':'选这家'}</button></div></div></article>`;}
function groupCard(event,i){const hotel=event.type==='hotel',key=event.key;return `<section class="event group-event ${hotel?'hotel-event':'meal-event'}" id="event-${i}" data-group="${key}" aria-label="${esc(event.title)}">${time(event,hotel?'住一晚':'吃一顿')}<div class="group-heading"><h3>${event.title}</h3><span class="count-label">${event.options.length} 选 1<span class="swipe-hint"> · 左右滑 →</span></span></div><p class="event-note">${event.note}</p><div class="option-rail ${hotel?'hotel-rail':''}" tabindex="0" aria-label="${esc(event.title)}，左右滑动比较选项">${event.options.map(id=>optionCard(id,key)).join('')}</div><p class="selection-line" data-selection="${key}">${picks[key]&&entry(picks[key])?'已选：'+entry(picks[key]).name:'照片可点开放大，查看出处与踩坑。'}</p></section>`;}
function driveCard(event,i){return `<article class="event" id="event-${i}">${time(event,'在路上')}<div class="drive-event"><h3>${event.title}</h3><p>${event.text}</p>${event.destination?`<button class="destination-preview" data-entry="${event.destination}" aria-label="查看今晚目的地酒店"><img loading="lazy" src="${entry(event.destination).image}" alt="今晚目的地 Sonora · Sonora Inn 客房照片" width="640" height="380"><small>今晚目的地 Sonora · 配图为 Sonora Inn 客房</small></button>`:''}</div></article>`;}
function render(scroll=false){routes();$('#days').innerHTML=dayNames.map((n,i)=>`<button class="day-tab" data-day="${i}" aria-pressed="${day===i}"><strong>${n} ${dayDates[i]}</strong><small>${dayTasks[i]}</small></button>`).join('');$('#day-kicker').textContent=`DAY 0${day+1} / ${route().name}`;$('#day-title').textContent=dayTitles[day];$('#day-summary').textContent=route().summary[day];const events=route().days[day];$('#timeline').innerHTML=events.map((e,i)=>e.type==='stop'?stopCard(e,i):e.type==='drive'?driveCard(e,i):groupCard(e,i)).join('');const jumps=events.map((e,i)=>({e,i})).filter(({e})=>e.type==='meal'||e.type==='hotel');$('#jump-links').innerHTML=jumps.map(({e,i})=>`<a href="#event-${i}">${e.type==='hotel'?'住宿':e.title.includes('早餐')?'早餐':e.title.includes('午餐')?'午餐':'晚餐'} ↓</a>`).join('');$('#drive-estimate').textContent=route().drive+' · 周日 09:30 前返程';if(scroll)$('#days').scrollIntoView({behavior:'smooth',block:'start'});}
function postLinks(ids){return ids.filter(id=>G.posts.some(p=>p.id===id)).map(id=>{const p=G.posts.find(p=>p.id===id);return `<a class="source-link" href="${p.url}" target="_blank" rel="noopener">${esc(p.author)} · ${esc(p.title)} ↗</a>`}).join('');}
function showDetail(){const e=entry(activeEntry);if(!e)return;const p=e.postId?G.posts.find(p=>p.id===e.postId):null;const point=e.pointId?G.points.find(p=>p.id===e.pointId):null;const ids=[...new Set([...(e.evidence||[]),...(point?.sources||[]),...(p?[p.id]:[])])];$('#detail-title').textContent=e.name;$('#detail-body').innerHTML=`${p?`<div class="media-tabs"><button data-media="photo" aria-pressed="${mediaMode==='photo'}">对应照片</button><button data-media="screen" aria-pressed="${mediaMode==='screen'}">原帖截图</button></div>`:''}<img class="detail-image" src="${mediaMode==='screen'&&p?p.screenshot:e.image}" alt="${esc(e.name)} · ${mediaMode==='screen'?'原帖面板截图':esc(e.credit)}"><div class="detail-text"><div class="credit">${esc(e.credit)}<br><a href="${e.photoSource}" target="_blank" rel="noopener">打开照片来源 ↗</a>${p?`<br>原帖显示：${esc(p.dateLabel)}；采集 2026/10/7。`:''}</div><p><b>${e.place}</b>${e.hint}</p><p><b>推荐 / 适合谁</b>${e.dish}</p><p class="pitfall"><b>踩坑 / 选择前看一眼</b>${e.pitfall}</p><div class="linkrow"><a href="${navUrl(e)}" target="_blank" rel="noopener">地图定位 ↗</a>${e.official?`<a href="${e.official}" target="_blank" rel="noopener">${['pass'].includes(e.id)?'路况':'官网 / 营业信息'} ↗</a>`:''}</div>${ids.length?`<details><summary>${ids.length} 篇推荐与踩坑原帖</summary>${postLinks(ids)}</details>`:''}<p class="source-note" style="margin-top:16px">照片保留真实来源，可能有后期或拍摄季节差异；不是实时路况。原帖打不开时，可查看上方保存的截图或完整来源页面。未查询实时余房，未执行预订。</p></div>`;}
function openDetail(id){activeEntry=id;mediaMode='photo';showDetail();document.body.classList.add('modal-open');$('#detail-dialog').showModal();}
function pick(id,key){picks[key]=picks[key]===id?null:id;try{localStorage.setItem('395-photo-guide-picks',JSON.stringify(picks))}catch{}const group=document.querySelector(`[data-group="${key}"]`);group.querySelectorAll('[data-pick]').forEach(b=>{const yes=picks[key]===b.dataset.pick;b.textContent=yes?'✓ 已选':'选这家';b.setAttribute('aria-pressed',String(yes));b.closest('.option-card').classList.toggle('chosen',yes)});group.querySelector('[data-selection]').textContent=picks[key]?'已选：'+entry(picks[key]).name:'照片可点开放大，查看出处与踩坑。';}
document.addEventListener('click',ev=>{const b=ev.target.closest('[data-route],[data-day],[data-entry],[data-media],[data-close],[data-pick]');if(!b)return;if(b.dataset.route){routeId=b.dataset.route;render()}else if(b.dataset.day!==undefined){day=Number(b.dataset.day);render(true)}else if(b.dataset.entry){openDetail(b.dataset.entry)}else if(b.dataset.media){mediaMode=b.dataset.media;showDetail()}else if(b.hasAttribute('data-close')){$('#detail-dialog').close()}else if(b.dataset.pick){pick(b.dataset.pick,b.dataset.key)}});
$('#detail-dialog').addEventListener('click',e=>{if(e.target===$('#detail-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}});
$('#detail-dialog').addEventListener('close',()=>document.body.classList.remove('modal-open'));
$('#back-to-plan').addEventListener('click',()=>$('#routes').scrollIntoView({behavior:'smooth',block:'start'}));
render();
